- README.md
- blockjoy/api/v1/node_types.proto
> feat: NodeStatus comprises now both, the container and chain status of a node

- blockjoy/api/ui_v1/command_service.proto
- blockjoy/api/ui_v1/common.proto
command service to be used by the UI. Each action on the UI should invoke one of the command available in this command service. The API will then create a corresponding command row and issue the appropriate BE command
> feat: added command service

- blockjoy/api/ui_v1/common.proto
added pagination object to request meta same as response meta for UI API
> feat: refactored pagination and added it to request meta

- blockjoy/api/ui_v1/authentication_service.proto
- blockjoy/api/ui_v1/user_service.proto
Move the password reset endpoints to the auth service
> Move the password reset endpoints to the auth service

- blockjoy/api/ui_v1/host_provision_service.proto
as requested in https://github.com/blockjoy/api-proto/issues/17
> feat: changed HostProvisionService.Get to accept either ID or not

- blockjoy/api/ui_v1/common.proto
Update blockchain message with supported_node_types and reorder fields.
> Update blockchain message with supported_node_types and reorder fields

- blockjoy/api/ui_v1/common.proto
- blockjoy/api/v1/node.proto
Changed NodeType to string so being able to store JSON
> feat: changed node type

- blockjoy/api/ui_v1/billing_service.proto
- blockjoy/api/ui_v1/blockchain_service.proto
- blockjoy/api/ui_v1/command_service.proto
- blockjoy/api/ui_v1/common.proto
- blockjoy/api/ui_v1/fe_host_service.proto
- blockjoy/api/ui_v1/node_service.proto
- blockjoy/api/ui_v1/organization_service.proto
- blockjoy/api/v1/command.proto
- blockjoy/api/v1/host.proto
- blockjoy/api/v1/messages.proto
- blockjoy/api/v1/node.proto
Replaced all Any typed values with string type
> feat: removed Any types

- blockjoy/api/ui_v1/common.proto
- blockjoy/api/v1/host.proto
- blockjoy/api/v1/node.proto
as described in https://app.shortcut.com/blockjoy/story/481/ip-range-management-for-nodes
> feat: added IP range and gateway where needed

- blockjoy/api/ui_v1/common.proto
- blockjoy/api/v1/key_file_service.proto
as described in https://app.shortcut.com/blockjoy/story/517/secure-transfer-of-node-keys
> feat: added keyfiles to node

- blockjoy/api/ui_v1/node_service.proto
as described in https://app.shortcut.com/blockjoy/story/588/node-filters-and-infinite-scroll-pagination
> feat: added filter criteria

- blockjoy/api/ui_v1/node_service.proto
https://app.shortcut.com/blockjoy/story/391/uat-node-deletion
> feat: added delete method to nodes

- blockjoy/api/ui_v1/user_service.proto
https://app.shortcut.com/blockjoy/story/354/delete-account
> feat: added delete method to user service

- blockjoy/api/ui_v1/organization_service.proto
https://app.shortcut.com/blockjoy/story/344/organization-management
> feat: added optional single org ID

- blockjoy/api/ui_v1/common.proto
- blockjoy/api/ui_v1/invitation_service.proto
- blockjoy/api/ui_v1/organization_service.proto
https://app.shortcut.com/blockjoy/story/810/organization-member-management
> feat: added invitation service

- blockjoy/api/ui_v1/common.proto
- blockjoy/api/ui_v1/invitation_service.proto
Joe needs to know the invitation id for each invitation returned from `ListPending`, so it seems to be a good idea to add an `id` to the `Invitation` message
> Add inivitation id to invitation

- blockjoy/api/ui_v1/common.proto
https://app.shortcut.com/blockjoy/story/876/add-host-name-to-node-view-screen
https://app.shortcut.com/blockjoy/story/875/provide-chain-network-configurations
> feat: added network configs, host_name to node

- blockjoy/api/ui_v1/authentication_service.proto
- blockjoy/api/ui_v1/common.proto
https://app.shortcut.com/blockjoy/story/903/organization-member-roles
> feat: added org user

- blockjoy/api/ui_v1/common.proto
Added renewed token to each UI response, so the UI can always use a valid one
> feat: added token to response

- blockjoy/api/ui_v1/common.proto
> feat: added white/black list IPs for nodes

- v1/host.proto
Removing unused field, task 1307
> #1307 - Removing unused field

- blockjoy/v1/mqtt.proto
To dynamically update the front end on the organisation page, we need to give Joe a way to subscribe to the invitations for that organisation. This pr adds 3 variants to the `OrgMessage` message to achieve this
> Mqtt invitations

- blockjoy/v1/command.proto
Explicitly require blockchain_net_type as node create argument
> feat: require blockchain_net_type as node create argument

- blockjoy/v1/command.proto
https://app.shortcut.com/blockjoy/story/1714/api-make-it-possible-implement-acknowledging-commands
> allow clients to acknowledge running commands

- blockjoy/v1/command.proto
- blockjoy/v1/host.proto
- blockjoy/v1/node.proto
proto cleanup according to BB Meeting
Story details: https://app.shortcut.com/blockjoy/story/1877
> chore: [sc-1877] Cleanup Commands Interface

- blockjoy/v1/cookbook.proto
Add service that gives host access to `DownloadeManifest` for given blockchain node, identified by config if and network.
> feat: [sc-1503] Add cookbook fn to download blockchain data files

- blockjoy/v1/user.proto
Also adds one bit of functionality: removing the billing id while keeping the user.
> Split the billing details out from the user message

- blockjoy/v1/cookbook.proto
Add separate service to work specifically with kernels. Old methods will be deprecated eventually
> feat: add KernelService

- blockjoy/v1/user.proto
https://app.shortcut.com/blockjoy/story/2681/user-search
> Add user filter

- blockjoy/v1/command.proto
Story details: https://app.shortcut.com/blockjoy/story/3122
> chore: [sc-3122] BV shall reject upgrade command while download/upload job is running

- blockjoy/v1/command.proto
https://app.shortcut.com/blockjoy/story/3326/node-command-log
> Allow users to filter commands

- blockjoy/v1/metrics.proto
Story details: https://app.shortcut.com/blockjoy/story/3298
> feat: [sc-3298] Make API aware of available resources on a host

- blockjoy/v1/blockchain.proto
- blockjoy/v1/metrics.proto
- rename standalone to dev-mode
> docs: More comprehensive bv node metrics [sc-3491]
